Добавление и обновление пользователей и фильмов
roman3350/java-filmorate pull request #4
Opened 2023-07-22 01:46 UTC by roman3350

добавлена возможность добавление, обновление и вывод добавленных фильмов
добавлена возможность добавление, обновление и вывод добавленных пользователей

2023-07-22 02:53 UTC, roman3350 commented
Совершенно не понимаю как удалить файл из пул реквеста, в последних коммитах его нет

2023-07-23 05:28 UTC, kriwsha requested changes

2023-07-23 05:28 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName() == null || film.getName().isBlank()) {
Я бы рекомендовал вынести валидацию в отдельный метод (и желательно в отдельный класс). Представьте, что вам потребуется еще добавлять проверки, тогда у вас будет разрастаться контроллер, что будет мешать читаемости кода.

2023-07-23 05:28 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail() == null || user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Здесь также я бы советовал вынести шаги валидации.

2023-08-08 12:52 UTC, merged